### ISSUE TITLE
enhancement/suggestion : add a car radio system 

### ISSUE THREAD

**Issue by Mesrine67** [Thomasdev18/ts_hud#9]
Would it be possible to add an auto radio template for vehicles? Then we could contribute to complete the system?
I'm thinking of creating a system similar to codem hud aio for its car radio system. 
and use this resource to control radios + add custom radios? https://github.com/Hellslicer/fivem-radio

**Comment by Thomasdev18** [comment]
Please don't create issues with suggestions.. add in in my discord please
